import { Router, Request, Response } from "express";
import { db } from "../db";
import {
  findUser,
  verifyPassword,
  loadUsers,
  createUser,
  deleteUser,
  updateUser,
  defaultPermissions,
  toPublicUser,
  PAGE_KEYS,
  hasAnySuperadmin,
  findSuperadmin,
  bootstrapSuperadmin,
} from "./userStore";
import { createSession, destroySession } from "./session";
import { SESSION_COOKIE_NAME, getSessionTokenFromRequest, requireAdminOrAbove } from "./middleware";

export const authRouter = Router();

function setSessionCookie(res: Response, token: string) {
  res.setHeader(
    "Set-Cookie",
    `${SESSION_COOKIE_NAME}=${token}; HttpOnly; Path=/; Max-Age=${24 * 60 * 60}; SameSite=Lax`
  );
}
function clearSessionCookie(res: Response) {
  res.setHeader("Set-Cookie", `${SESSION_COOKIE_NAME}=; HttpOnly; Path=/; Max-Age=0; SameSite=Lax`);
}

// ---------- First-run setup ----------
// No password is ever generated by the server — the very first superadmin account is
// created here with a password the person types themselves. This endpoint only works
// once, ever: it's a genuine first-run bootstrap, not a general "add superadmin" route.
authRouter.get("/needs-setup", (_req: Request, res: Response) => {
  res.json({ needsSetup: !hasAnySuperadmin() });
});

authRouter.post("/setup-superadmin", (req: Request, res: Response) => {
  const { username, password } = req.body ?? {};
  if (!username || !password) return res.status(400).json({ error: "username and password are required" });
  if (password.length < 8) return res.status(400).json({ error: "Password must be at least 8 characters." });
  if (hasAnySuperadmin()) {
    return res.status(409).json({ error: "A superadmin account already exists — setup has already run." });
  }
  try {
    const admin = bootstrapSuperadmin(username, password);
    const token = createSession({ siteName: null, username: admin.username, role: "superadmin", permissions: {} });
    setSessionCookie(res, token);
    res.status(201).json({ username: admin.username, role: "superadmin", permissions: {}, siteName: null });
  } catch (e: any) {
    res.status(409).json({ error: String(e?.message ?? e) });
  }
});

// ---------- Login ----------
// siteName is optional: a superadmin isn't scoped to any one site, so it's ignored for
// them. Admin/user accounts do need it, since the same username could exist independently
// on more than one site.
authRouter.post("/login", (req: Request, res: Response) => {
  const { siteName, username, password } = req.body ?? {};
  if (!username || !password) {
    return res.status(400).json({ error: "username and password are required" });
  }

  const superadmin = findSuperadmin(username);
  if (superadmin && verifyPassword(password, superadmin.salt, superadmin.hash)) {
    const token = createSession({ siteName: null, username: superadmin.username, role: "superadmin", permissions: {} });
    setSessionCookie(res, token);
    return res.json({ username: superadmin.username, role: "superadmin", permissions: {}, siteName: null });
  }

  if (!siteName) {
    return res.status(400).json({ error: "Site name is required (unless logging in as Super Admin)." });
  }

  // Resolve against the actual sites table first (case-insensitive, trimmed) rather than
  // blindly slugifying whatever was typed — the two would otherwise only match if the
  // typed string produces byte-for-byte the same slug as when the account was created
  // (e.g. "Test Site" vs "TestSite" slugify to "test-site" vs "testsite" — different
  // folders, so an account that genuinely exists would silently fail to be found here).
  const siteRow = db
    .prepare("SELECT name FROM sites WHERE LOWER(TRIM(name)) = LOWER(TRIM(?))")
    .get(siteName) as { name: string } | undefined;
  const canonicalSiteName = siteRow?.name ?? siteName;

  const user = findUser(canonicalSiteName, username);
  if (!user || !verifyPassword(password, user.salt, user.hash)) {
    // Deliberately vague — don't reveal whether the site/username/password specifically was wrong.
    return res.status(401).json({ error: "Invalid site name, username, or password." });
  }
  const token = createSession({ siteName: canonicalSiteName, username: user.username, role: user.role, permissions: user.permissions });
  setSessionCookie(res, token);
  res.json({ username: user.username, role: user.role, permissions: user.permissions, siteName: canonicalSiteName });
});

authRouter.post("/logout", (req: Request, res: Response) => {
  destroySession(getSessionTokenFromRequest(req));
  clearSessionCookie(res);
  res.status(204).end();
});

authRouter.get("/me", (req: Request, res: Response) => {
  if (!req.user) return res.status(401).json({ error: "Not authenticated" });
  const { siteName, username, role, permissions } = req.user;
  res.json({ siteName, username, role, permissions });
});

// ---------- User management (admin manages their own site's users; superadmin manages any site's, plus can create admins) ----------

/** Resolves which site's users.json a request should operate on, and rejects anything an
 *  admin (not superadmin) tries that's outside their own site or role bounds. Centralizes
 *  the one piece of logic every user-management route below needs. */
function resolveTargetSite(req: Request, bodyOrQuerySiteName: unknown): { siteName: string } | { error: string; status: number } {
  if (req.user!.role === "admin") {
    // Admins are locked to their own site regardless of what they pass — prevents an
    // admin from reaching into another site's users by guessing/sending a different name.
    return { siteName: req.user!.siteName! };
  }
  // superadmin
  if (!bodyOrQuerySiteName || typeof bodyOrQuerySiteName !== "string") {
    return { error: "siteName is required for a superadmin request.", status: 400 };
  }
  return { siteName: bodyOrQuerySiteName };
}

authRouter.get("/users", requireAdminOrAbove, (req: Request, res: Response) => {
  const resolved = resolveTargetSite(req, req.query.site);
  if ("error" in resolved) return res.status(resolved.status).json({ error: resolved.error });
  res.json(loadUsers(resolved.siteName).map(toPublicUser));
});

authRouter.post("/users", requireAdminOrAbove, (req: Request, res: Response) => {
  const { username, password, role, permissions, siteName } = req.body ?? {};
  if (!username || !password || !role) {
    return res.status(400).json({ error: "username, password and role are required" });
  }
  if (role !== "admin" && role !== "user") {
    return res.status(400).json({ error: "role must be 'admin' or 'user'" });
  }
  if (req.user!.role === "admin" && role === "admin") {
    return res.status(403).json({ error: "Only a superadmin can create another admin." });
  }

  const resolved = resolveTargetSite(req, siteName);
  if ("error" in resolved) return res.status(resolved.status).json({ error: resolved.error });

  try {
    const user = createUser(resolved.siteName, username, password, role, permissions ?? defaultPermissions(role));
    res.status(201).json(toPublicUser(user));
  } catch (e: any) {
    res.status(400).json({ error: String(e?.message ?? e) });
  }
});

authRouter.put("/users/:username", requireAdminOrAbove, (req: Request, res: Response) => {
  const { role, permissions, password, siteName } = req.body ?? {};
  if (role && role !== "admin" && role !== "user") {
    return res.status(400).json({ error: "role must be 'admin' or 'user'" });
  }
  if (req.user!.role === "admin" && role === "admin") {
    return res.status(403).json({ error: "Only a superadmin can promote someone to admin." });
  }

  const resolved = resolveTargetSite(req, siteName);
  if ("error" in resolved) return res.status(resolved.status).json({ error: resolved.error });

  try {
    const user = updateUser(resolved.siteName, req.params.username, { role, permissions, password });
    res.json(toPublicUser(user));
  } catch (e: any) {
    res.status(400).json({ error: String(e?.message ?? e) });
  }
});

authRouter.delete("/users/:username", requireAdminOrAbove, (req: Request, res: Response) => {
  const resolved = resolveTargetSite(req, req.query.site);
  if ("error" in resolved) return res.status(resolved.status).json({ error: resolved.error });

  if (
    req.user!.role !== "superadmin" &&
    req.user!.username.toLowerCase() === req.params.username.toLowerCase()
  ) {
    return res.status(400).json({ error: "You can't delete your own account while logged in as it." });
  }
  deleteUser(resolved.siteName, req.params.username);
  res.status(204).end();
});

// So the frontend's permission-editor grid knows what pages exist without hardcoding them twice.
authRouter.get("/page-keys", requireAdminOrAbove, (_req: Request, res: Response) => {
  res.json(PAGE_KEYS);
});
